---
- name: install pip
  sudo: yes
  apt: name=python-pip

- name: install virtualenv
  sudo: yes
  pip: name=virtualenv

- name: create virtualenv
  sudo: yes
  sudo_user: "{{virtualenv_user}}"
  command: virtualenv env
  args:
    chdir: "{{virtualenv_path}}/"
    creates: "{{virtualenv_path}}/env"
