---
- name: Add NodeSource PPA for latest version of Node.js.
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Ensure Node.js and npm are installed.
  sudo: yes
  apt: name=nodejs state=present
