---
- name: install postgres
  sudo: yes
  action: apt name={{item}}
  with_items:
    - postgresql-{{postgres_version}}
    - libpq-dev
    - python-psycopg2

- name: create project database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{db_name}}

- name: grant access to database for project user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}}

- name: ensure project user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: create script folder if not exist
  sudo: yes
  sudo_user: "{{db_user}}"
  file: path={{script_dir}} state=directory

- name: create pg env script
  sudo: yes
  sudo_user: "{{db_user}}"
  template: >-
    src=pg_env.sh.j2
    dest={{script_dir}}/pg_env.sh
    mode=755
    owner={{db_user}}

  # optionally open the access for outside if running inside vagrant
- name: open pg outside access
  sudo: yes
  lineinfile: >-
    dest=/etc/postgresql/{{postgres_version}}/main/postgresql.conf
    line="listen_addresses = '*'"
  lineinfile: >-
    dest=/etc/postgresql/{{postgres_version}}/main/pg_hba.conf
    line="host all all 10.0.2.2/24 trust"
  when: vagrant_env is defined and vagrant_env == true
  notify:
    - restart postgres
