---
- name: install postgres
  sudo: yes
  action: apt name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: create project database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{db_name}}

- name: grant access to database for project user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}}

- name: ensure project user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB
