---
# for pg 9.4
- name: create postgres apt source list file
  sudo: yes
  template: >-
    src=pgdg.list
    dest=/etc/apt/sources.list.d/pgdg.list

- name: download apt key for pgdg
  sudo: yes
  get_url: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc dest=/tmp/ACCC4CF8.asc

- name: add apt key for postgres source
  sudo: yes
  apt_key: id=ACCC4CF8 url=file:///tmp/ACCC4CF8.asc state=present

- name: install postgres
  sudo: yes
  action: apt name={{item}} update_cache=yes
  with_items:
    - postgresql-{{postgres_version}}
    - libpq-dev
    - python-psycopg2

- name: create project database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{db_name}}

- name: check if pg password is generated already
  sudo: yes
  sudo_user: "{{db_user}}"
  stat: path={{pg_password_file}}
  when: pg_random_password
  register: pg_password_stat
  changed_when: False

- name: generate pg password
  sudo: yes
  sudo_user: "{{db_user}}"
  when: pg_random_password and not pg_password_stat.stat.exists
  shell: date | md5sum | head -c 32 > {{pg_password_file}}

- name: register pg password
  sudo: yes
  sudo_user: "{{db_user}}"
  when: pg_random_password
  command: cat {{pg_password_file}}
  register: pg_password_data
  changed_when: False

- set_fact:
    db_password: "{{pg_password_data.stdout}}"
  when: pg_random_password

- name: grant access to database for project user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{db_name}} name={{db_user}} password={{db_password}}

- name: ensure project user does not have unnecessary privilege
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: create script folder if not exist
  sudo: yes
  sudo_user: "{{db_user}}"
  file: path={{script_dir}} state=directory

- name: create pg env script
  sudo: yes
  sudo_user: "{{db_user}}"
  template: >-
    src=pg_env.sh
    dest={{script_dir}}/pg_env.sh
    mode=755
    owner={{db_user}}

  # optionally open the access for outside if running inside vagrant
- name: allow pg to listen on all addresses
  sudo: yes
  lineinfile: >-
    dest=/etc/postgresql/{{postgres_version}}/main/postgresql.conf
    line="listen_addresses = '*'"
  when: vagrant_env is defined and vagrant_env == true
  notify:
    - restart postgres

- name: allow pg to trust connection from outside vagrant
  sudo: yes
  lineinfile: >-
    dest=/etc/postgresql/{{postgres_version}}/main/pg_hba.conf
    line="host all all 10.0.2.2/24 trust"
  when: vagrant_env is defined and vagrant_env == true
  notify:
    - restart postgres
