---
- name: clone nvm
  sudo: yes
  sudo_user: "{{project_user}}"
  git: >-
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    update=no
    accept_hostkey=yes

- name: source nvm in .profile
  sudo: yes
  sudo_user: "{{project_user}}"
  lineinfile: >-
    dest=~/.profile
    line=". ~/.nvm/nvm.sh"

- name: check current user shell
  sudo: yes
  command: sudo -iu {{project_user}} echo $SHELL
  register: node_user_shell
  changed_when: False

- name: change user shell to bash
  sudo: yes
  user: name={{project_user}} shell=/bin/bash
  changed_when: False

- name: install nodejs using nvm
  sudo: yes
  command: sudo -iu {{project_user}} nvm install {{node_version}}
  register: nvm_install_result
  changed_when: nvm_install_result.stdout.find('is already installed.') != -1

- name: set default nodejs version
  command: sudo -iu {{project_user}} nvm alias default {{node_version}}
  changed_when: False

- name: change back to user default shell
  sudo: yes
  user: name={{project_user}} shell={{node_user_shell.stdout}}
  changed_when: False
