---
- name: install webupd8 oracle java PPA
  sudo: yes
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: add key for webupd8 oracle java PPA
  sudo: yes
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886

- name: automatically select the Oracle License
  sudo: yes
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: install oracle JDK 7
  sudo: yes
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes
