---
- name: start postgres docker container
  docker:
    name: "{{pg_docker_container_name}}"
    image: "postgres:{{pg_docker_version}}"
    state: restarted
    ports:
      - "{{pg_docker_port}}:5432"
    env:
      POSTGRES_PASSWORD: "{{pg_docker_password}}"

- name: create script folder if not exist
  file: path={{script_dir}} state=directory

- name: create pg env script
  template: >-
    src=pg_env.sh
    dest={{script_dir}}/pg_env.sh
    mode=755
