---
- name: start postgres docker container
  docker:
    name: some-postgres
    image: "postgres:{{pg_docker_version}}"
    state: restarted
    ports:
      - "{{pg_docker_port}}:5432"
    env:
      POSTGRES_PASSWORD: "{{pg_docker_password}}"
