---
- name: create schemup config directory
  sudo: yes
  sudo_user: "{{project_user}}"
  when: db_schemup_path is defined
  file: path={{db_schemup_path}} state=directory

- name: generate schemup db config file
  sudo: yes
  sudo_user: "{{project_user}}"
  when: db_schemup_path is defined
  template: src=db.json dest={{db_schemup_path}}/db.json

- name: install python-dev
  sudo: yes
  apt: name=python-dev

- name: create schemup virtualenv
  sudo: yes
  sudo_user: "{{project_user}}"
  command: virtualenv env
  args:
    chdir: ~/
    creates: ~/env

- name: copy schemup requirements file to server
  sudo: yes
  sudo_user: "{{project_user}}"
  copy: src=requirements.txt dest=~/schemup-requirements.txt

- name: install schemup requirements
  sudo: yes
  sudo_user: "{{project_user}}"
  pip: requirements=~/schemup-requirements.txt virtualenv=~/env

- name: run schemup
  sudo: yes
  sudo_user: "{{project_user}}"
  when: db_schemup_path is defined
  command: ~/env/bin/schemup commit
  args:
    chdir: "{{db_schemup_path}}"
