---
- name: create schemup config directory
  sudo: yes
  sudo_user: "{{schemup_user}}"
  when: schemup_path is defined
  file: path={{schemup_path}} state=directory

- name: generate schemup db config file
  sudo: yes
  sudo_user: "{{schemup_user}}"
  when: schemup_path is defined
  template: src=db.json dest={{schemup_path}}/db.json

- name: install python-dev
  sudo: yes
  apt: name=python-dev

- name: create virtualenv if not exist
  sudo: yes
  sudo_user: "{{schemup_user}}"
  command: virtualenv env
  args:
    chdir: "{{virtualenv_path}}"
    creates: "{{virtualenv_path}}/env"

- name: copy schemup requirements file to server
  sudo: yes
  sudo_user: "{{schemup_user}}"
  copy: src=requirements.txt dest=~/schemup-requirements.txt

- name: install schemup requirements
  sudo: yes
  sudo_user: "{{schemup_user}}"
  pip: requirements=~/schemup-requirements.txt virtualenv={{virtualenv_path}}/env

- name: run schemup
  sudo: yes
  sudo_user: "{{schemup_user}}"
  when: schemup_path is defined
  command: "{{virtualenv_path}}/env/bin/schemup commit"
  args:
    chdir: "{{schemup_path}}"
  register: schemup_result
  changed_when: schemup_result.stdout.find('Creating') != -1 or schemup_result.stderr.find('Upgrading') != -1
